config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  get 'about', to: "about#index"
  get 'dashboard', to: "artists#show"

  resources :artists, only: [:edit, :update]
  resources :venues, only: [:show]
  resources :events
  resources :tours, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :events, only: [:new, :create]
  end

  get '/login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get '/register', to: redirect('/auth/google_oauth2'), as: 'register'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name, :google_token, :email, :google_client_id
  has_many :tours
  has_many :events, through: :tours

  def self.find_or_create_from_auth_hash(auth)
    artist = find_or_create_by(google_client_id: auth["uid"])
  	artist.name = auth["info"]["first_name"]
  	artist.email = auth["info"]["email"]
    artist.google_token = auth["credentials"]["token"]
  	artist.save
    artist
  end

  def future_tours
    tours.map do |tour|
      if tour.future_events? == true
        tour
      end
    end.compact
  end

  def past_tours
    tours.map do |tour|
      if tour.past_events? == true
        tour
      end
    end.compact
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name, :show_time
  belongs_to :tour

  def self.future_events
    now = Time.now.strftime("%m-%d-%Y")
    x = Event.where("show_date > ?", now)
  end

  def self.past_events
    now = Time.now.strftime("%m-%d-%Y")
    y = Event.where("show_date < ?", now)
  end

  def self.event_gains(tour)
    profit_totals = []
    z = Event.where(tour_id: tour)
    z.each do |e|
      profit_totals << e.event_profit
    end
    profit_totals.sum.to_f
  end

  def self.travel_cost(tour)
    travel_expenses = []
    y = Event.where(tour_id: tour)
    y.each do |e|
      travel_expenses << e.travel_cost
    end
    travel_expenses.sum.to_f
  end

  def artist?
    tour.artist
  end

  def total_profit
    total = (event_profit - travel_cost)
    total
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  validates_presence_of :name
  belongs_to :artist
  has_many :events, dependent: :destroy

  def future_events_list
    events.map do |event|
      if event.show_date > Time.now
        event
      end
    end.compact
  end

  def past_events_list
    events.map do |event|
      if event.show_date < Time.now
        event
      end
    end.compact
  end

  def past_events?
    if past_events_list.count != 0
      true
    else
      false
    end
  end

  def future_events?
    if future_events_list.count != 0
      true
    else
      false
    end
  end

  def start_date
    first_event = Event.order('show_date ASC').first
    if first_event
      first_event.show_date
    end
  end

  def end_date
    first_event = Event.order('show_date DESC').first
    if first_event
      first_event.show_date
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_artist

  def current_artist
    @current_artist ||= Artist.find(session[:artist_id]) if session[:artist_id]
  end

  def current_artist?(artist)
    current_artist == artist
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def show
    @current_artist = current_artist
    @future_tours = current_artist.future_tours
    @past_tours = current_artist.past_tours
  end

  def edit
    @current_artist = current_artist
  end

  def update
    current_artist.band_name = params[:artist][:band_name]
    current_artist.save
    redirect_to dashboard_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def new
    @tour = Tour.find_by(id: params[:tour_id])
    @events = @tour.events.new
    @venues = service_venue.find_venues_by_city(params[:q])
  end

  def show
    @current_artist = current_artist
    @event = Event.find(params[:id])
    if @event.artist?
      @venue = service_venue.find_single_venue_by_id(@event.venue_id)
    else
      render file: '/public/404'
    end
  end

  def edit
    @event = Event.find(params[:id])
    if @event.artist? == current_artist
      @event
    else
      render file: '/public/404'
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] =  "#{@event.name} was successfully updated!"
      redirect_to @event
    else
      render :new
    end
  end

  def create
    tour = current_artist.tours.find_by(id: params[:tour_id])
    event = tour.events.create!(event_params)
    flash[:alert] = "Succesfully created #{event.name}!" if event
    redirect_to new_tour_event_path      
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:alert] = "Succesfully deleted #{@event.name}!"
    redirect_to tour_path(@event.tour)
  end

  private

  def event_auth
    @event.tour.artist_id == current_artist.id
  end

  def event_params
    params.require(:event).permit(:name, :show_time, :venue_id, :show_date, :event_profit, :travel_cost)
  end

  def service_venue
    VenueBuilderFacade.new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @artist = Artist.find_or_create_from_auth_hash(request.env["omniauth.auth"])
    session[:artist_id] = @artist.id
    redirect_to dashboard_path
  end

  def destroy
    session[:artist_id] = nil
    redirect_to root_path
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

  def new
    @tour = Tour.new()
  end

  def create
    tour = current_artist.tours.create(tour_params)

    redirect_to "/tours/#{tour.id}/events/new"
  end

  def show
    @tour = current_artist.tours.find(params[:id])
    @events = @tour.events
  end

  def destroy
    tour = current_artist.tours.find(params[:id])
    tour.destroy
    redirect_to dashboard_path
  end

  def edit
    @tour = current_artist.tours.find(params[:id])
  end

  def update
    tour = current_artist.tours.find(params[:id])
    tour.name = params[:tour][:name]
    tour.save!
    redirect_to tour_path(tour)
  end

  private

  def  tour_params
    params.require(:tour).permit(:name)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def show
    @events = Event.where(venue_id: params[:id])
    @venue ||= @venue = VenueBuilderFacade.new.find_single_venue_by_id(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/about/index.html.erb
<div class="box">
  <h1>On The Road Again</h1>
  <h1><u>Team Github Profiles</u></h1>
    <h1><%= link_to "Jimmy Smith", "https://github.com/JSmith23" %></h1>
    <h1><%= link_to "Nick Lindeberg", "https://github.com/NickLindeberg" %></h1>
    <h1><%= link_to "Silvestre Cuellar", "https://github.com/SiCuellar" %></h1>
    <h1><u>Project Github Repo</u></h1>
    <h1><%= link_to "On The Road Again", "https://github.com/NickLindeberg/on_the_road_again" %></h1>
    <h1><u>Venue API</u></h1>

    <h1><%= link_to "Songkick", "https://www.songkick.com/developer" %></h1>
</div>

app/views/artists/edit.html.erb
<div class="box">
  <h1>Edit Band Details </h1>
  <%= form_for @current_artist do |f| %>

  <h3><%= f.label 'Band Name' %></h3>
  <%= f.text_field :band_name, class:"input-group-text", id:"inputGroup-sizing-lg"  %><br>
    <br>
  <%= f.submit "Let's Roll!", class:"btn btn-info btn-lg" %>
  <% end %>
</div>

app/views/artists/show.html.erb
<div class="container-fluid">
  <% if @current_artist.band_name %>
  <div class="row">
    <h1 class="band-name col-lg"> <%= @current_artist.band_name %> </h1>
  </div>
<% else  %>
<%= link_to "Add New Band Details!", edit_artist_path(@current_artist.id), :class => "btn btn-info btn-lg"  %>
<% end  %>

  <%= link_to "Add New Tour", new_tour_path, :class => "btn btn-info btn-lg"  %>

  <div class="row">
    <div class="tours col-lg">
      <h2>Past Tours</h2>
        <%  @past_tours.each do |tour| %>
          <div class="p-tours">
            <%= link_to "#{tour.name}", tour_path(tour.id), :class => "btn btn-info btn-lg btn-block"  %>
            <p class = "btn btn-outline-danger btn-sm"><%= link_to "Delete Tour", {:controller => :tours, :action => 'destroy', :id => tour.id },
              :method => :delete %></p>
              <% if tour.start_date %>
                <h4>Start Date: <%= tour.start_date.to_date %></h4>
                <h4>End Date: <%= tour.end_date.to_date %></h4>
              <% end %>
          </div>
            <br>
        <% end %>

    </div>

    <div class="tours col-lg">
      <h2>Future Tours</h2>
        <% @future_tours.each do |tour| %>
        <div class="f-tours">
          <%= link_to "#{tour.name}", tour_path(tour.id), :class => "btn btn-info btn-lg btn-block"  %>
          <p class = "btn btn-outline-danger btn-sm"><%= link_to "Delete Tour", {:controller => :tours, :action => 'destroy', :id => tour.id },
            :method => :delete %></p>
            <% if tour.start_date %>
              <h4>Start Date: <%= tour.start_date.to_date %></h4>
              <h4>End Date: <%= tour.end_date.to_date %></h4>
            <% end %>
          </div>
          <br>
          <% end  %>
        </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="form-box">
  <h1>Edit <%= @event.name %></h1>
  <%= form_for(@event) do |f| %>
     <div class="form-group">
      <%= f.text_field :name, placeholder: "Event Name", class:"input-group-text", id:"inputGroup-sizing-lg" %>
    </div>
    <div class="form-group">
      <%= f.date_field :show_date, class:"input-group-text", id:"inputGroup-sizing-lg" %>
    </div>
    <div class="form-group">
      <%= f.text_field :show_time, placeholder: "Show Time", class:"input-group-text", id:"inputGroup-sizing-lg"  %>
    </div>
    <br>
      <%= f.submit class:"btn btn-info btn-lg" %>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="form-box">
  <h1 class="band-name"><%= @tour.name %></h1>
  <h1>Search For Venues</h1>
  <%= form_for [@tour, @events], :remote => true do |e| %>
    <div class="form-group">
      <button id="myBtn" class="btn btn-info btn-lg" type="button">Search City</button>
    </div>
    <br>
    <div class="form-group">
      <%= e.select :venue_id, options_for_select(@venues.map{|ven| ["#{ven.name}", ven.name, ven.songkick_id]}, :style => "width:70px" ) %>
    </div>
    <div class="form-group">
      <%= e.text_field :name, placeholder: "Event Name", class:"input-group-text", id:"inputGroup-sizing-lg" %>
    </div>
    <div class="form-group">
      <%= e.date_field :show_date, placeholder: "Event Date", class:"input-group-text", id:"inputGroup-sizing-lg" %>
    </div>
    <div class="form-group">
      <%= e.text_field :show_time, placeholder: "Show Time", class:"input-group-text", id:"inputGroup-sizing-lg"  %>
    </div>
    <br>
      <%= e.submit class:"btn btn-info btn-lg" %>
  <% end %>

  <br>

  <%= link_to "Tour Booked", dashboard_path, class:"btn btn-info btn-lg" %>

  <h1>Scheduled Events</h1>
    <% @tour.events.each do |event| %>
      <h2><%= event.name %></h2>
      <h2><%= event.show_date.to_s.to_date %></h2>
      <h2><%= event.show_time %></h2>
      <br>
    <% end %>

  <div id="myModal" class="modal">
    <div class="modal-content">
      <h3>Enter A City To Find Venues</h3>
      <span class="close">&times;</span>

      <%= form_tag :new_tour_event, method: :get, class: "form" do %>
          <%= text_field_tag :q, ""%>
          <br>
          <%= submit_tag "Locate", class: "btn btn-info btn-lg"%>
      <% end %>
  </div>
</div>


 <script>
 // Get the modal
 var modal = document.getElementById('myModal');

 // Get the button that opens the modal
 var btn = document.getElementById("myBtn");

 // Get the <span> element that closes the modal
 var span = document.getElementsByClassName("close")[0];

 var search = document.getElementById("search");

 // When the user clicks the button, open the modal
 btn.onclick = function() {
   modal.style.display = "block";
 }

 // When the user clicks on <span> (x), close the modal
 span.onclick = function() {
   modal.style.display = "none";
 }
 </script>

app/views/events/show.html.erb
<div class="box">
  <h1> <%= @event.name %> </h1>
  <section class="Event info">
  <h2>Where: <%= link_to @venue.name, venue_path(@venue.songkick_id), :class => "btn btn-info btn-lg" %></h2>
  <h3>Date: <%= @event.show_date.to_date  %> </h3>
  <h3>Time: <%= @event.show_time  %></h3>
    <section class="stats">
  <% if @current_artist && @event.event_profit != 0 %>
    <h2><u>Event Statistics</u></h2>
    <h3>Gig Profit: <%=number_to_currency(@event.event_profit)  %></h3>
    <h3>Travel cost: <%=number_to_currency(@event.travel_cost)  %></h3>
    <h3>Total Profit: <%= number_to_currency(@event.total_profit, precision: 2) %></h3>

  <% elsif @current_artist && @event.show_date.past? %>
      <h2>Add Profit Statistics</h2>
      <%= form_for @event do |f| %>

      <div class="form-group">
        <h3><%= f.label 'Gig Profit' %><br></h3>
        <%= f.number_field :event_profit, step: 0.01, placeholder: 0.00,  class:"input-group-text", id:"inputGroup-sizing-lg" %><br>
      </div>
      <div class="form-group">
        <h3><%= f.label 'Travel Cost' %></h3>
        <%= f.number_field :travel_cost, step: 0.01,  class:"input-group-text", id:"inputGroup-sizing-lg" %><br>
      </div>
      <%= f.submit "Calculate Profit", class:"btn btn-info btn-lg" %>
    <% end %>
    </section>
  <% else  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnTheRoadAgain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-outline-info">
    <a class="navbar-brand" href="/">On The Road Again</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if current_artist %>
        <li class="nav-item">
          <a class="nav-link" href="/dashboard">Dashboard</a>
        </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>
        <% if current_artist %>
        <li class="nav-logout">
          <a class="nav-link" href="/logout">Log Out</a>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <body>
        <% if flash[:notice] %>
          <p class="flash notice">
             <%= flash[:notice] %>
          </p>
        <% end %>

        <% if flash[:alert] %>
          <p class="flash alert">
             <%= flash[:alert] %>
          </p>
        <% end %>

    <%= yield %>
  </body>

  <footer>
    <div class="footer">
      <a href="https://www.songkick.com/developer/venue-details">
        <%= image_tag "songkick.png", class: "foot" %>
      </a>
  </div>
  </footer>
</html>

app/views/tours/edit.html.erb
<div class="box">
  <h2>Edit Tour Name</h2>
    <%= form_for @tour do |f| %>

    <%= f.text_field :name, class:"input-group-text", id:"inputGroup-sizing-lg" %><br>

    <%= f.submit "Update", class:"btn btn-info btn-lg" %>
  <% end %>
</div>

app/views/tours/new.html.erb
<div class="box">

  <h1>Tour Name</h1>
  <%= form_for @tour do |b| %>
     <div class="form-group">
       <%= b.text_field :name, class:"input-group-text", id:"inputGroup-sizing-lg"%>
     </div>
     <div><%= b.submit class:"btn btn-info mb-2" %></div>
  <% end %>
</div>

app/views/tours/show.html.erb
<div class="container">
  <div class="row">
    <div class ="tour-box">
    <div class="col-lg">

    <h1><%= @tour.name%></h1>
      <h3>By: <%= @tour.artist.band_name %></h3>
      <p class ="d-inline btn btn-outline-info btn-sm"><%= link_to "Edit Tour", edit_tour_path(@tour) %></p>

      <% @tour.events.each do |event| %>
        <% if event.show_date > Time.now %>
          <h2><%= link_to event.name, event_path(event) %></h2>
          <p class ="d-inline btn btn-outline-info btn-lg"><%= link_to "Edit Event", edit_event_path(event) %></p>
          <p class ="d-inline btn btn-outline-danger btn-lg"><%= link_to "Delete Event", event_path(event), method: :delete %></p>
        <% else %>
          <h2><%= link_to event.name, event_path(event) %></h2>
          <h4>Event was <%= distance_of_time_in_words_to_now(event.show_date) %> ago!</h4>
        <% end %>
      <% end %>
      </div>
  </div>

    <div class="tour-box">
    <div class="col-lg">
      <h1><%= @tour.name%> Statistics</h1>
      <h2>Total Revenue:</h2>
      <h3><%= number_to_currency(@events.event_gains(@tour)) %></h3>
      <h2>Total Expenses</h2>
      <h3><%= number_to_currency(@events.travel_cost(@tour)) %></h3>
      <h2>Net Profit</h2>
      <h3><%= number_to_currency(@events.event_gains(@tour) - @events.travel_cost(@tour)) %></h3>
    </div>
  </div>
  </div>
</div>

app/views/venues/show.html.erb
<div class="box">
  <h1><%=@venue.name %> Show Page</h1>

    <ul>
      <h3><%= @venue.name%></h3>
      <h3><%= @venue.address%></h3>
      <% if @venue.website %>
        <h3><%= link_to @venue.website, @venue.website%></h3>
      <% end %>
      <h3><%= @venue.phone%></h3>
    </ul>
    <div class="future-tours col-lg">
        <h2>Future Events:</h2>
        <div class="f-tours">
          <% @events.future_events.each do |event| %>
            <h3><%= event.name %></h3>
            <% end %>
            <% if @events.future_events.count < 1 %>
              <h2>Currently no forthcoming events.</h2>
            <% end %>
        </div>
      </div>
      <div class="past-tours col-lg">
        <h2>Past Events:</h2>
        <div class="p-tours">
          <% @events.past_events.each do |event| %>
              <h3><%= link_to event.name, event_path(event.id) %></h3>
            <% end %>
          <% if @events.past_events.count < 1 %>
            <h2>Currently no past events.</h2>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>


<% unless current_artist %>
<h1>Please Login or Register!</h1>
  <%= link_to "Login/Register", register_path, :class => "btn btn-info btn-lg"  %>
<% end %>

<div class="logo">
  <%= image_tag("logo.png") %>
</div>